### PR TITLE
Hacks for nvhpc build

### PR DESCRIPTION
**Pull request by rchen20**

### CODE REVIEW

**Comment by rchen20** [comment]
Need to find the right CMake compiler ID for nvhpc to enable the `-Mnomain` flag to `add_link_options()` for test_driver.

**Comment by rennich** [comment]
Hello Robert –

I am ‘reviewing’ these.  (‘reviewing’ = my ability to detect performance or quality issues just by reading code is vanishingly close to zero)

I hope to try this on lassen … ‘soon’.  That’s when I’ll provide an actual ‘review’.

Can you comment:


  1.  Does this result in a running build of UMT?
     *   That is, it seems some of the 3rd party libs revert to using the GCC toolchain?  Which is fine?  Because they are just needed for setup?
     *   But UMT and … I think it’s required … mfem use the nvhpc tools?
  2.  Does this running build offload to the GPUs on Lassen?

Thanks,
Steve


From: Robert Chen ***@***.***>
Date: Monday, September 11, 2023 at 10:54 AM
To: LLNL/UMT ***@***.***>
Cc: Steven Rennich ***@***.***>, Review requested ***@***.***>
Subject: Re: [LLNL/UMT] Hacks for nvhpc build (PR #15)

Need to find the right CMake compiler ID for nvhpc to enable the -Mnomain flag to add_link_options() for test_driver.

**Comment by rchen20** [comment]
Hey @rennich,

> 1.  Does this result in a running build of UMT?
>     *   That is, it seems some of the 3rd party libs revert to using the GCC toolchain?  Which is fine?  Because they are just needed for setup?
>     *   But UMT and … I think it’s required … mfem use the nvhpc tools?

This produces a running build of UMT on the CPU only. It uses the nvhpc compilers on Lassen, and I have not tried this with pure gcc. The upgrade to gcc/8.3.1 is required to resolve C++ std library symbols that 4.9.3 doesn't have.

I can also clean the script up, and make it a little more generic so that it can run on multiple platforms. Barring that, I could also just put this particular build process into its own script.

>  2.  Does this running build offload to the GPUs on Lassen?

Unfortunately, it only works on the CPU because Umpire is not built with the `build_and_run_umt.sh` script. I'd need to spend some time to get that to work (maybe with @aaroncblack 's help), but you should be able to get some relevant performance metrics from the pure CPU runs? Maybe we can talk about your goals for this.

**Comment by rchen20** [comment]
Closing because these hacks are no longer needed due to https://github.com/LLNL/UMT/pull/17.

**Pull request closed without merging**
